Repository AY2425S2-CS2103T-T16-4/tp, pull requests merged in 2025-04, with the labels that each got.

#108 Change the links of Ui.java, Logic.java, Model.java and Storage.java in Developer Guide
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/Main.java
Labels: alpha-bug

#120 Update links in DeveloperGuide and DevOps
  docs/DevOps.md
  docs/DeveloperGuide.md
Labels: alpha-bug

#118 Enhance email logic and update tests with edge cases
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: alpha-bug

#114 Add test for ListCommand with empty AddressBook
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: alpha-bug

#128 Fix PayStatus reflecting wrong colour on UI
  src/main/java/seedu/address/logic/commands/UnpayCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/PayStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PayStatusTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: alpha-bug

#134 UG update
  docs/UserGuide.md
Labels: alpha-bug

#136 Enhancement of UG
  docs/UserGuide.md
Labels: type.Enhancement

#138 Phone fix
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: alpha-bug

#144 Add appropriate message for empty list
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnpayCommand.java
  src/test/java/seedu/address/logic/commands/UnpayCommandTest.java
Labels: alpha-bug

#149 Implement FilterPaidStatusCommand and FilterSubjectCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterDateCommand.java
  src/main/java/seedu/address/logic/commands/FilterPaidStatusCommand.java
  src/main/java/seedu/address/logic/commands/FilterSubjectCommand.java
  src/main/java/seedu/address/logic/commands/UnpayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterPaidStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterSubjectCommandParser.java
  src/main/java/seedu/address/model/person/PayStatusEqualsPaidPredicate.java
  src/main/java/seedu/address/model/person/SubjectContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterPaidStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterSubjectCommandTest.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterPaidStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterSubjectCommandParserTest.java
  src/test/java/seedu/address/model/person/PayStatusEqualsPaidPredicateTest.java
  src/test/java/seedu/address/model/person/SubjectContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#140 Add current time check to NextLesson
  src/main/java/seedu/address/logic/parser/NextLessonCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/logic/parser/NextLessonCommandParserTest.java
Labels: alpha-bug

#157 Add test for NextLessonParser & Fix Duplicate phone logic
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/parser/NextLessonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PayCommandParserTest.java
Labels: alpha-bug

#161 Refactor persons to students in displayed text
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FilterDateCommand.java
  src/main/java/seedu/address/logic/commands/FilterPaidStatusCommand.java
  src/main/java/seedu/address/logic/commands/FilterSubjectCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
Labels: alpha-bug

#168 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: alpha-bug

#255 Fix NextLesson prefix problem
  src/main/java/seedu/address/logic/commands/NextLessonCommand.java
  src/main/java/seedu/address/logic/parser/NextLessonCommandParser.java
  src/test/java/seedu/address/logic/commands/NextLessonCommandTest.java
  src/test/java/seedu/address/logic/parser/NextLessonCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug
